var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xx                                                                            ",
   "  x                              oo                                             ",
   "  x                              xxyy               xxxx                        ",
   "  x                                       oo oo     ooox                        ",
   "  x                                       xxxxx      oox                        ",
   "  x@                                                  ox                    xx  ",
   "  xx                            xxyy                                         x  ",
   "  x                H    o # o                 o   o            yy            x  ",
   "  x                     xxxxx                 xxxxx                          x  ",
   "  x       yy                                                  o   o          x  ",
   "  x                                                           xxxxx          x  ",
   "  xxxxxx      xxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxx  ",
   "       x     x    x  x                                                          ",
   "       xoooox     xvvx                                                          ",
   "       xxxxx      xvvx                                                          ",
   "                  xvvx                                                          ",
   "                  xxxx                                                          ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "x                                                                                                                 ",
   "x                                          ooooo                                                                  ",
   "x                                          xxxxx                                                                  ",
   "x             oo                               x                                                                  ",
   "x             xx                               x     x                                      xx                    ",
   "xo            x                                xo  H xo                  o                   x                    ",
   "xxxxxxx       x    H                           xx    xx            H    xxx                  x                    ",
   "x             x                                x     x                   x                   x                    ",
   "x             x               xxx              x     x                   x  H                x                    ",
   "x            ox                 x              x!!!!!xxxxxxxxxxxxx       x   xxxxxxxxx      xx                    ",
   "x            xx       xx        x              xxxxxxx                   x   x               x                    ",
   "x    @       x         x        x              x                         x   x               x                    ",
   "xxxxxxxxxxxxxx         x       ox              x                         xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx!!!!!!!!!xo                                x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x      xx     xx!!!!!!!!xx    x  H      o o o  #  o o o   x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x          H   xxxxxxxxxx     x       xxxxxxxxxxxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x                            xx      xx                      xx o o xx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                     xx      xx                        xxxxxxx                      ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx  ooo  xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                          x                                                                   ",
   "                                          x                                                                   ",
   "                                          x                                                                   ",
   "                               xxxxxxxxxxxx                                                                   ",
   "                               x                                                                              ",
   "                               x      H   o   o       xxxx                                   x                ",
   "                               x          xxxxx       x                                      x                ",
   "                               xxxxxx             ooo x        H   H   H                     x                ",
   "                               x               xxxxxxxx                      o o   H  H      x                ",
   "                               x                      x                     xxxxx            x                ",
   "                               x     xx               x                                      x                ",
   "                               x o    x         H     x                                     ox                ",
   "                               xxxxxxxxxxxxx          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx                ",
   "                               x!x!x!x!x!x!x        oox!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "                               xx x x x x xx       xxxxxxxxxxxxxxxxxxxxxxxxx                                  ",
   "  xxx                          xx!!!!!!!!!xxx                              x                                  ",
   "  x                            x!!!!!!!!!!!x                               x                              x   ",
   "  x    H                  x    x!!!!xxx!!!!x                               x                              x   ",
   "  x                       x    xxxxxxxxxxxxxxxxxxx                         xxxxx                          x   ",
   "  x                       x    x            x                              x!!!x                          x   ",
   "  xx x x x x x x          xxxxxx            xoooo                          x!!!x                          x   ",
   "  xx!x!x!x!x!x!x!xxx   H  x               H xxxxx H  xxxx H xxxx  H x    xxxxxxx                          x   ",
   "  x x x x x x x x  x      xo                                         x                                    x   ",
   "  x                x      xx                                          x              ooo  H  H      H     x   ",
   "  x                x               xxx                                 x             xxx                  x   ",
   "  x                x                                                             x!!!x                    x   ",
   "  x                xx                                                             xxx                     x   ",
   "  x                          xxxxxxxxxxx    x    x    x    x    x     xx xx                     xx        x   ",
   "  x      @                   x          xx!!x!!!!x!!!!x!!!!x!!!!x!!!!xx!!!xx                    x#        x   ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                                                       xxx                                    ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          x       x                                                                           ",
   "                          x       x                                                                           ",
   "                          x       x                                                                           ",
   "                          x       x                                                                           ",
   "                          x       x                                                                           ",
   "                          x       x              x                                                            ",
   "                           x     x               x                                                            ",
   "                            x @ x    xxx  x  x   x                                                            ",
   "                             xxx    x   x x  x   x                                                            ",
   "                              x      xxx   xx    x                                                            ",
   "                              x                  x                                                            ",
   "                              x  x   x  o  x  x  x                                                            ",
   "                              x  x   x     xx x  x                                                            ",
   "                              x  x x x  x  x xx                                                               ",
   "                              x   x x   x  x  x  x                                                            ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
